import type { IncidentView } from "./incident-view";
import { ROLE_LABELS } from "./result-schema";
import { formatInTz } from "./time";

/** Render the closing summary as Markdown. Phone numbers are masked; provider ids are kept. */
export function renderIncidentMarkdown(view: IncidentView): string {
  const { incident, card, tasks, recoveryActions, audit } = view;
  const tz = incident.timezone;
  const lines: string[] = [];
  lines.push(`# DockSignal incident ${incident.id}`);
  lines.push("");
  lines.push(`- Shipment: ${incident.shipmentRef}`);
  lines.push(`- Cargo: ${incident.cargoDescription}`);
  lines.push(`- Promised dock time: ${incident.promisedDockDisplay}`);
  if (incident.receivingCutoffDisplay) lines.push(`- Receiving cutoff on file: ${incident.receivingCutoffDisplay}`);
  lines.push(`- Last known location at intake: ${incident.lastKnownLocation}`);
  lines.push(`- Status: ${incident.status}${incident.closedAt ? ` (closed ${formatInTz(incident.closedAt, tz)})` : ""}`);
  lines.push(`- Operator: ${incident.operatorName}`);
  lines.push(`- Organisation represented on calls: ${incident.orgName}`);
  lines.push("");
  lines.push(`## Recovery card`);
  lines.push("");
  lines.push(`**Situation:** ${card.branchLabel}`);
  lines.push("");
  lines.push(`**Confidence:** ${card.confidence.label}`);
  for (const r of card.confidence.reasons) lines.push(`- ${r}`);
  lines.push("");
  lines.push("| Fact | Status | Value | Sources |");
  lines.push("| --- | --- | --- | --- |");
  for (const f of card.facts) {
    const sources = f.sources.map((s) => `${ROLE_LABELS[s.role]} (${s.providerCallId ?? s.taskId})`).join(", ") || "none";
    lines.push(`| ${f.label} | ${f.status} | ${(f.value ?? "unresolved").replace(/\|/g, "/")} | ${sources} |`);
  }
  lines.push("");
  if (card.eta.etaDisplay || card.eta.cutoffDisplay) {
    lines.push(`ETA analysis: ETA ${card.eta.etaDisplay ?? "unresolved"}, cutoff ${card.eta.cutoffDisplay ?? "unknown"}${card.eta.cutoffSource ? ` (${card.eta.cutoffSource === "dock_call" ? "from dock call" : "from intake"})` : ""}${card.eta.minutesLate !== null ? `, ${card.eta.minutesLate} minutes relative to cutoff` : ""}.`);
    lines.push("");
  }
  if (card.unresolvedTasks.length) {
    lines.push("### Unresolved sources");
    lines.push("");
    for (const u of card.unresolvedTasks) lines.push(`- ${ROLE_LABELS[u.role]} ${u.contactName}: ${u.reason} (status ${u.status})`);
    lines.push("");
  }
  lines.push("## Recovery actions");
  lines.push("");
  if (!recoveryActions.length) lines.push("- none");
  for (const a of recoveryActions) {
    lines.push(`- [${a.status}] ${a.title} — owner: ${a.owner}${a.requiresCall ? "; CALL-E follow-up call" : "; manual"}${a.approvedBy ? `; approved by ${a.approvedBy} at ${formatInTz(a.approvedAt, tz)}` : ""}`);
    lines.push(`  - Why: ${a.rationale}`);
  }
  lines.push("");
  lines.push("## Calls (provider-backed)");
  lines.push("");
  for (const t of tasks) {
    lines.push(`### ${t.kind === "follow_up" ? "Follow-up" : "Fact-finding"}: ${ROLE_LABELS[t.role]} ${t.contactName} (${t.phoneMasked})`);
    lines.push("");
    lines.push(`- DockSignal status: ${t.status}`);
    lines.push(`- CALL-E call id: ${t.providerCallId ?? "not created"}`);
    lines.push(`- Provider status: ${t.providerStatus ?? "n/a"}; recipient status: ${t.recipientStatus ?? "n/a"}`);
    lines.push(`- Idempotency key: ${t.idempotencyKey}`);
    if (t.approvedBy) lines.push(`- Human approval: ${t.approvedBy} at ${formatInTz(t.approvedAt, tz)}`);
    if (t.summary) lines.push(`- CALL-E summary: ${t.summary}`);
    if (t.taskCompleted !== null) lines.push(`- Task completed: ${t.taskCompleted}${t.completionConfidence ? ` (confidence ${t.completionConfidence.label}, ${t.completionConfidence.score})` : ""}`);
    if (t.evidence.length) {
      lines.push("- Evidence:");
      for (const e of t.evidence) lines.push(`  - ${e}`);
    }
    if (t.structuredResult) {
      lines.push("- Structured result:");
      for (const [k, v] of Object.entries(t.structuredResult)) lines.push(`  - ${k}: ${v === "" ? "(empty)" : v}`);
    }
    if (t.lastError) lines.push(`- Error: ${t.lastError}`);
    if (t.transcript.length) {
      lines.push("- Transcript:");
      for (const turn of t.transcript) lines.push(`  - [${turn.offset_seconds ?? "?"}s] ${turn.speaker}: ${turn.text}`);
    }
    lines.push("");
  }
  lines.push("## Decision log");
  lines.push("");
  for (const a of audit) lines.push(`- ${formatInTz(a.createdAt, tz)} — ${a.actor}: ${a.action} ${JSON.stringify(a.detailJson)}`);
  lines.push("");
  lines.push(`_Generated by DockSignal at ${formatInTz(new Date(), tz)}. Every fact above links to a CALL-E call id; unknown, failed, and validation-failed results were never treated as facts._`);
  return lines.join("\n");
}
